ALTER TABLE clients   ENABLE ROW LEVEL SECURITY;
ALTER TABLE servers   ENABLE ROW LEVEL SECURITY;
ALTER TABLE ports     ENABLE ROW LEVEL SECURITY;
ALTER TABLE softwares ENABLE ROW LEVEL SECURITY;
ALTER TABLE links     ENABLE ROW LEVEL SECURITY;
